[project]
name = "exp-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arxiv>=2.2.0",
    "bhakti>=0.2.19",
    "python-dotenv>=0.9.0",
    "firebase-admin>=7.1.0",
    "jinja2>=3.1.6",
    "markdownify>=1.1.0",
    "openai>=1.97.0",
    "pandas>=2.3.1",
    "psycopg>=3.2.9",
    "pydantic>=2.11.7",
    "qdrant-client>=1.15.0",
    "requests>=2.32.4",
    "sqlparse>=0.5.3",
    "together>=1.5.21",
    "django>=5.1.3",
    "langchain-mistralai>=0.2.2",
    "langchain>=0.3.9",
    "matplotlib>=3.9.2",
    "python-telegram-bot>=21.7",
    "ollama>=0.5.3",
    "supabase>=2.18.1",
]
