from llm.LLM import LanguageModel
from agentic.AgentMemory import MemoryEngine
from agentic.prompt_constructor import PromptConstructor
import json
from typing import List, Callable

class Agent:
    def __init__(
        self,
        agent_id: str,
        agent_desc: str,
        signature: PromptConstructor,
        tools = List[Callable] 
    ):
        self.agent_id = agent_id
        self.agent_desc = agent_desc,
        self.llm_inst:LanguageModel = None
        self.signature = signature
        self.memory = ""
        self.prompt = self.signature.construct_prompt()
    def run(self, user_input: str, temp:int = 0.6):
        """
        Executes the agent's logic given a user input and retrieves a model-generated result.

        This method performs the following steps:
        1. Retrieves relevant memory based on the user input.
        2. Fills the prompt template with user input and memory context.
        3. Queries the language model for a response.

        Args:
            user_input (str): The user's current message or query.
            memory (str): (Optional) Additional memory string, currently unused.

        Returns:
            str: The response generated by the language model.
        """
        if self.memory is not None:
            runnable_memory = self.memory.retrieve(self.agent_id, query=user_input)
        runnable_memory = ""
        self.signature.fill_prompt(user_input, runnable_memory)
        return self.llm_inst.get_result(self.signature, temp=temp)

    def run_func(self, call_result:str):
        parsed = json.loads(call_result)
        tool_name = parsed["tool_name"]
        tool = next((t for t in self.tools_allowed if t.name == tool_name))
        return tool.run(call_result)

    def configure(self, model_inst = LanguageModel)->None:
        self.llm_inst = model_inst

    def attach_memory(self, memory_engine:MemoryEngine):
        self.memory = memory_engine
