from llm.LLM import LanguageModel
from agentic.AgentMemory import MemoryEngine
from agentic.prompt_constructor import PromptConstructor
from typing import List
from agentic.Tooling import BaseTooling
import json

class Agent:
    """
    Represents an autonomous agent that interacts with a language model using 
    memory, prompt engineering, and optional tooling.

    Attributes:
        agent_desc (str): A textual description of the agent's role or purpose.
        llm_inst (LanguageModel): The language model instance used for text generation.
        signature (PromptConstructor): An instance to construct and fill prompts.
        memory (MemoryEngine): The memory system to retrieve contextual data.
        prompt (str): The current prompt string, constructed based on memory and input.
    """

    def __init__(
        self,
        agent_id: str,
        agent_desc: str,
        llm_inst: LanguageModel,
        signature: PromptConstructor,
        memory: MemoryEngine = None,
        tools_allowed = List[BaseTooling]
    ):
        """
        Initializes the Agent with its configuration and constructs an initial prompt.

        Args:
            agent_id (str): Unique identifier for the agent (used for memory operations).
            agent_desc (str): Description of the agent's purpose.
            llm_inst (LanguageModel): A language model interface for generating responses.
            signature (PromptConstructor): PromptConstructor instance for prompt formatting.
            memory (MemoryEngine): MemoryEngine instance for storing and retrieving past context.
        """
        self.agent_id = agent_id
        self.agent_desc = agent_desc
        self.llm_inst = llm_inst
        self.signature = signature
        self.tools_allowed = tools_allowed
        self.signature.get_toolList(tools_allowed)
        self.memory = memory
        self.prompt = self.signature.construct_prompt()
    def run(self, user_input: str, temp:int = 0.6):
        """
        Executes the agent's logic given a user input and retrieves a model-generated result.

        This method performs the following steps:
        1. Retrieves relevant memory based on the user input.
        2. Fills the prompt template with user input and memory context.
        3. Queries the language model for a response.

        Args:
            user_input (str): The user's current message or query.
            memory (str): (Optional) Additional memory string, currently unused.

        Returns:
            str: The response generated by the language model.
        """
        if self.memory is not None:
            runnable_memory = self.memory.retrieve(self.agent_id, query=user_input)
        runnable_memory = ""
        self.signature.fill_prompt(user_input, runnable_memory)
        return self.llm_inst.get_result(self.signature, temp=temp)

    def run_func(self, call_result:str):
        parsed = json.loads(call_result)
        tool_name = parsed["tool_name"]
        tool = next((t for t in self.tools_allowed if t.name == tool_name))
        return tool.run(call_result)        
